[package]
name = "snake"
version = "0.2.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.5"
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }
lazy_static = "1.5"
